import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My IMDb Clone', //show on the tab
  description: 'IMDb clone website. Generated by NextJS.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* HEADER */}
        <Header />
        {/* NAVBAR */}

        {/* SEARCH BAR */}

        {children}
      </body>
    </html>
  )
}
